/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.2
  Forc version: 0.68.7
  Fuel-Core version: 0.43.1
*/

import {
  Account,
  BigNumberish,
  BN,
  decompressBytecode,
  Script as __Script,
} from 'fuels';

export type TestScriptInputs = [input: BigNumberish];
export type TestScriptOutput = BN;

const abi = {
  "programType": "script",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "name": "main",
      "inputs": [
        {
          "name": "input",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0",
      "attributes": null
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const bytecode = decompressBytecode('H4sIAAAAAAAAAzVRPUsDQRB9CQceNq4aJZxfV6hYCiL4UXjLXTi/DlYkaHPc2lmGQ8QyP0ELP0pLy73OMqWlpeW1QoJ2RlLEd0ncZua9mXmzb9f5XscVYGFwysPAGPdbJdHvw2kr3KEs1FmmLjyMJx3sMVqM28rPuio0DV2DzVxrKWwVZh8Fjn2zG0uAfbLI0wD2XFDxhLQ8crvkJGdvmE9w9nI0+6/1XmD27DifgNvdwHkvL6tebvGuh8nXu8ealwYWVgOAOk9JuzGd7lvc51aSNmZ0R1TJv+nQVNVRdqMPCpy5uuYSm+oQm2aB49CI+NRMxkdmKj2GLaLl1ky0ietjlLhvjFx5LgpaqWLtZBOrClhbqDSdoAERVZpJBKQea3IZ1M6TjphPOt4CvS0q36xryZ1hZtNbld5u6a3A+QjnzLeGudkf1owpMD3OqpoQ1OxSa0lJ1x68k2/41q7g3Av7BDVeyQtdh4ilKsV1hZU6cA+UHmwM/tDxczg/z3B+gSdyj6wddoE/pHz4IAACAAA=');

export class TestScript extends __Script<TestScriptInputs, TestScriptOutput> {

  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(wallet: Account) {
    super(bytecode, abi, wallet);
  }
}
