/* Autogenerated file. Do not edit manually. */

/* eslint-disable max-classes-per-file */
/* eslint-disable @typescript-eslint/no-unused-vars */
/* eslint-disable @typescript-eslint/consistent-type-imports */

/*
  Fuels version: 0.101.2
  Forc version: 0.68.7
  Fuel-Core version: 0.43.1
*/

import {
  BigNumberish,
  BN,
  decompressBytecode,
  InputValue,
  Predicate as __Predicate,
  PredicateParams,
  Provider,
} from 'fuels';

export type TestPredicateConfigurables = undefined;

export type TestPredicateInputs = [password: BigNumberish];

export type TestPredicateParameters = Omit<
  PredicateParams<TestPredicateInputs, TestPredicateConfigurables>,
  'abi' | 'bytecode'
>;

const abi = {
  "programType": "predicate",
  "specVersion": "1",
  "encodingVersion": "1",
  "concreteTypes": [
    {
      "type": "bool",
      "concreteTypeId": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903"
    },
    {
      "type": "u64",
      "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
    }
  ],
  "metadataTypes": [],
  "functions": [
    {
      "name": "main",
      "inputs": [
        {
          "name": "password",
          "concreteTypeId": "1506e6f44c1d6291cdf46395a8e573276a4fa79e8ace3fc891e092ef32d1b0a0"
        }
      ],
      "output": "b760f44fa5965c2474a3b471467a22c43185152129295af588b022ae50b50903",
      "attributes": [
        {
          "name": "doc-comment",
          "arguments": [
            " This predicate checks if the given password is 1337."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " If it is, the predicate is 'unlocked' and the transaction is allowed to proceed."
          ]
        },
        {
          "name": "doc-comment",
          "arguments": [
            " Otherwise, it is reverted."
          ]
        }
      ]
    }
  ],
  "loggedTypes": [],
  "messagesTypes": [],
  "configurables": [],
  "errorCodes": {}
};

const bytecode = decompressBytecode('H4sIAAAAAAAAAzVQvUoDQRD+NjllMadZOIuwNkEsLAOCaLfHJZzEZssUnp6dpYpY+woW/jyAD7CP4KNcG0ggRQIJKS7fhs3CsjPz/czM6lkPb0CE7RF29xb1v1B1DT2x+AQ+XgyaD1PExa2LH9NT2Nx17geAzVznLgUS3ncDtctf+2gkaWRYE5d0pGZI/RHxZ2pVOYBk3C1TJZmf+5xz7JMXk3dI7KmckuOx3HluL3Cvgnbk8yJzrYL9qGn7mH3lSf/YKPZmrcVamxrJWFBjgsdN8LDB40CPge7yAqN11bDrKuIs4mwOfAHNb4ntP+is4l5710n+Z/RCQa+AX2I/5AyXQM49N8EqVP5QAQAA');

export class TestPredicate extends __Predicate<
  TestPredicateInputs,
  TestPredicateConfigurables
> {
  static readonly abi = abi;
  static readonly bytecode = bytecode;

  constructor(params: TestPredicateParameters) {
    super({ abi, bytecode, ...params });
  }
}
